# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_setting_B.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Setting(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(709, 499)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(70, 420, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(146, 255, 252);")
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(40, 240, 171, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.radioButton_scratch_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_scratch_1.setGeometry(QtCore.QRect(10, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.radioButton_scratch_1.setFont(font)
        self.radioButton_scratch_1.setStyleSheet("background-color: rgb(255, 7, 7);")
        self.radioButton_scratch_1.setObjectName("radioButton_scratch_1")
        self.radioButton_scratch_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_scratch_2.setGeometry(QtCore.QRect(10, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_scratch_2.setFont(font)
        self.radioButton_scratch_2.setStyleSheet("background-color: rgb(236, 255, 21);")
        self.radioButton_scratch_2.setObjectName("radioButton_scratch_2")
        self.radioButton_scratch_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_scratch_3.setGeometry(QtCore.QRect(10, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_scratch_3.setFont(font)
        self.radioButton_scratch_3.setStyleSheet("background-color: rgb(16, 255, 84);")
        self.radioButton_scratch_3.setObjectName("radioButton_scratch_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 70, 171, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_ppoint_1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ppoint_1.setGeometry(QtCore.QRect(10, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.radioButton_ppoint_1.setFont(font)
        self.radioButton_ppoint_1.setStyleSheet("background-color: rgb(255, 7, 7);")
        self.radioButton_ppoint_1.setObjectName("radioButton_ppoint_1")
        self.radioButton_ppoint_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ppoint_2.setGeometry(QtCore.QRect(10, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ppoint_2.setFont(font)
        self.radioButton_ppoint_2.setStyleSheet("background-color: rgb(236, 255, 21);")
        self.radioButton_ppoint_2.setObjectName("radioButton_ppoint_2")
        self.radioButton_ppoint_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ppoint_3.setGeometry(QtCore.QRect(10, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ppoint_3.setFont(font)
        self.radioButton_ppoint_3.setStyleSheet("background-color: rgb(16, 255, 84);")
        self.radioButton_ppoint_3.setObjectName("radioButton_ppoint_3")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(490, 70, 171, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_burr_1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_burr_1.setGeometry(QtCore.QRect(10, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.radioButton_burr_1.setFont(font)
        self.radioButton_burr_1.setStyleSheet("background-color: rgb(255, 7, 7);")
        self.radioButton_burr_1.setObjectName("radioButton_burr_1")
        self.radioButton_burr_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_burr_2.setGeometry(QtCore.QRect(10, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_burr_2.setFont(font)
        self.radioButton_burr_2.setStyleSheet("background-color: rgb(236, 255, 21);")
        self.radioButton_burr_2.setObjectName("radioButton_burr_2")
        self.radioButton_burr_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_burr_3.setGeometry(QtCore.QRect(10, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_burr_3.setFont(font)
        self.radioButton_burr_3.setStyleSheet("background-color: rgb(16, 255, 84);")
        self.radioButton_burr_3.setObjectName("radioButton_burr_3")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(260, 70, 171, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_ppoint_1_ring = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ppoint_1_ring.setGeometry(QtCore.QRect(10, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.radioButton_ppoint_1_ring.setFont(font)
        self.radioButton_ppoint_1_ring.setStyleSheet("background-color: rgb(255, 7, 7);")
        self.radioButton_ppoint_1_ring.setObjectName("radioButton_ppoint_1_ring")
        self.radioButton_ppoint_2_ring = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ppoint_2_ring.setGeometry(QtCore.QRect(10, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ppoint_2_ring.setFont(font)
        self.radioButton_ppoint_2_ring.setStyleSheet("background-color: rgb(236, 255, 21);")
        self.radioButton_ppoint_2_ring.setObjectName("radioButton_ppoint_2_ring")
        self.radioButton_ppoint_3_ring = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_ppoint_3_ring.setGeometry(QtCore.QRect(10, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_ppoint_3_ring.setFont(font)
        self.radioButton_ppoint_3_ring.setStyleSheet("background-color: rgb(16, 255, 84);")
        self.radioButton_ppoint_3_ring.setObjectName("radioButton_ppoint_3_ring")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setGeometry(QtCore.QRect(260, 240, 171, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.radioButton_scratch_1_ring = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_scratch_1_ring.setGeometry(QtCore.QRect(10, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.radioButton_scratch_1_ring.setFont(font)
        self.radioButton_scratch_1_ring.setStyleSheet("background-color: rgb(255, 7, 7);")
        self.radioButton_scratch_1_ring.setObjectName("radioButton_scratch_1_ring")
        self.radioButton_scratch_2_ring = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_scratch_2_ring.setGeometry(QtCore.QRect(10, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_scratch_2_ring.setFont(font)
        self.radioButton_scratch_2_ring.setStyleSheet("background-color: rgb(236, 255, 21);")
        self.radioButton_scratch_2_ring.setObjectName("radioButton_scratch_2_ring")
        self.radioButton_scratch_3_ring = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_scratch_3_ring.setGeometry(QtCore.QRect(10, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_scratch_3_ring.setFont(font)
        self.radioButton_scratch_3_ring.setStyleSheet("background-color: rgb(16, 255, 84);")
        self.radioButton_scratch_3_ring.setObjectName("radioButton_scratch_3_ring")
        self.pushButton_setting_level = QtWidgets.QPushButton(Dialog)
        self.pushButton_setting_level.setGeometry(QtCore.QRect(270, 420, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_setting_level.setFont(font)
        self.pushButton_setting_level.setStyleSheet("")
        self.pushButton_setting_level.setObjectName("pushButton_setting_level")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(310, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(550, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(180, 197, 255);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Save"))
        self.groupBox.setTitle(_translate("Dialog", "Scratch"))
        self.radioButton_scratch_1.setText(_translate("Dialog", "level 1"))
        self.radioButton_scratch_2.setText(_translate("Dialog", "level 2"))
        self.radioButton_scratch_3.setText(_translate("Dialog", "level 3"))
        self.groupBox_2.setTitle(_translate("Dialog", "PPoint"))
        self.radioButton_ppoint_1.setText(_translate("Dialog", "level 1"))
        self.radioButton_ppoint_2.setText(_translate("Dialog", "level 2"))
        self.radioButton_ppoint_3.setText(_translate("Dialog", "level 3"))
        self.groupBox_3.setTitle(_translate("Dialog", "Burr"))
        self.radioButton_burr_1.setText(_translate("Dialog", "level 1"))
        self.radioButton_burr_2.setText(_translate("Dialog", "level 2"))
        self.radioButton_burr_3.setText(_translate("Dialog", "level 3"))
        self.groupBox_4.setTitle(_translate("Dialog", "PPoint"))
        self.radioButton_ppoint_1_ring.setText(_translate("Dialog", "level 1"))
        self.radioButton_ppoint_2_ring.setText(_translate("Dialog", "level 2"))
        self.radioButton_ppoint_3_ring.setText(_translate("Dialog", "level 3"))
        self.groupBox_6.setTitle(_translate("Dialog", "Scratch"))
        self.radioButton_scratch_1_ring.setText(_translate("Dialog", "level 1"))
        self.radioButton_scratch_2_ring.setText(_translate("Dialog", "level 2"))
        self.radioButton_scratch_3_ring.setText(_translate("Dialog", "level 3"))
        self.pushButton_setting_level.setText(_translate("Dialog", "setting level"))
        self.label.setText(_translate("Dialog", "Center"))
        self.label_2.setText(_translate("Dialog", "Ring"))
        self.label_3.setText(_translate("Dialog", "Edge"))

